In [5]:
import pandas as pd
import numpy as np

In [6]:
movies_data=pd.read_csv(r"../data/raw/tmdb_5000_movies.csv")
credits_data=pd.read_csv(r"../data/raw/tmdb_5000_credits.csv")

In [7]:
movies_data.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [8]:
credits_data.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [9]:
movies_data=movies_data[['genres','id','keywords','overview','title','tagline']]

In [10]:
movies_data.head(3)

,genres,id,keywords,overview,title,tagline
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,Enter the World of Pandora.
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,A Plan No One Escapes

In [11]:
credits_data=credits_data[['title','cast','crew']]
movies=movies_data.merge(credits_data,on="title")

In [12]:
movies.isna().sum()

genres        0
id            0
keywords      0
overview      3
title         0
tagline     844
cast          0
crew          0
dtype: int64

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
import ast 

def convert(obj):
    if isinstance(obj, str):   # only convert if string
        obj = ast.literal_eval(obj)
    l=[]
    for item in obj:
        l.append(item['name'])
    return l

In [16]:
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [18]:
movies.head()

,genres,id,keywords,overview,title,tagline,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"Lost in our world, found in another.","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [20]:
def main_person(obj):
    l=[]
    count=0
    for item in ast.literal_eval(obj):
        if count!=3:
            l.append(item['name'])
            count+=1
        else:
            break
    return l

In [21]:
# movies['cast']=movies['cast'].apply(main_person)

movies.head(2)

,genres,id,keywords,overview,title,tagline,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [22]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [23]:
def director(obj):
    for i in ast.literal_eval(obj):
        if (i['job']=="Director"):
            return [i['name']]

In [24]:
director(movies.iloc[0].crew)

['James Cameron']

In [25]:
movies['crew']=movies['crew'].apply(director)

In [26]:
movies.head(4)

,genres,id,keywords,overview,title,tagline,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]

In [27]:
tags=movies['genres']+movies['keywords']

print(tags[0])

TypeError: can only concatenate str (not "list") to str

In [ ]:

movies['overview'] = movies['overview'].fillna('')
movies['overview']=movies['overview'].apply(lambda x: x.split( ) )

In [ ]:
movies.head()

,genres,id,keywords,overview,title,tagline,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,Enter the World of Pandora.,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,A Plan No One Escapes,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,The Legend Ends,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"Lost in our world, found in another.","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [ ]:
movies['tagline'] = movies['tagline'].fillna('')
movies['tagline']=movies['tagline'].apply(lambda x: x.split( ) )

In [ ]:
movies.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
# movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']+movies['tagline']

In [ ]:
# movies=movies[["id",'title','tags']]

In [ ]:
movies.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
movies['tags'] = movies['tags'].apply(lambda x: x if isinstance(x, list) else [])

movies['tags']=movies['tags'].apply(lambda x: [i.replace(" ","") for i in x])

In [ ]:
movies.iloc[0].tags

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron',
 'Enter',
 'the',
 'World',
 'of',
 'Pandora.']

In [ ]:
movies.head(2)

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."

In [ ]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [ ]:
movies['tags'][0]

'i n   t h e   2 2 n d   c e n t u r y ,   a   p a r a p l e g i c   m a r i n e   i s   d i s p a t c h e d   t o   t h e   m o o n   p a n d o r a   o n   a   u n i q u e   m i s s i o n ,   b u t   b e c o m e s   t o r n   b e t w e e n   f o l l o w i n g   o r d e r s   a n d   p r o t e c t i n g   a n   a l i e n   c i v i l i z a t i o n .   a c t i o n   a d v e n t u r e   f a n t a s y   s c i e n c e f i c t i o n   c u l t u r e c l a s h   f u t u r e   s p a c e w a r   s p a c e c o l o n y   s o c i e t y   s p a c e t r a v e l   f u t u r i s t i c   r o m a n c e   s p a c e   a l i e n   t r i b e   a l i e n p l a n e t   c g i   m a r i n e   s o l d i e r   b a t t l e   l o v e a f f a i r   a n t i w a r   p o w e r r e l a t i o n s   m i n d a n d s o u l   3 d   s a m w o r t h i n g t o n   z o e s a l d a n a   s i g o u r n e y w e a v e r   j a m e s c a m e r o n   e n t e r   t h e   w o r l d   o f   p a n d o r a .'

In [ ]:
movies['tags']=movies['tags'].apply(lambda x: x.lower())

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(max_features=5000,stop_words=None)

# cv.fit_transform(movies['tags']).toarray()
movies['tags'].head()

0    i n   t h e   2 2 n d   c e n t u r y ,   a   ...
1    c a p t a i n   b a r b o s s a ,   l o n g   ...
2    a   c r y p t i c   m e s s a g e   f r o m   ...
3    f o l l o w i n g   t h e   d e a t h   o f   ...
4    j o h n   c a r t e r   i s   a   w a r - w e ...
Name: tags, dtype: str

In [ ]:
movies['tags'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Name: tags, Length: 4779, dtype: bool

In [ ]:
movies = movies[movies['tags'] != ""]

NameError: name 'movies' is not defined

In [ ]:
movies['tags']

0       i n   t h e   2 2 n d   c e n t u r y ,   a   ...
1       c a p t a i n   b a r b o s s a ,   l o n g   ...
2       a   c r y p t i c   m e s s a g e   f r o m   ...
3       f o l l o w i n g   t h e   d e a t h   o f   ...
4       j o h n   c a r t e r   i s   a   w a r - w e ...
                              ...
4804    e l   m a r i a c h i   j u s t   w a n t s   ...
4805    a   n e w l y w e d   c o u p l e ' s   h o n ...
4806    " s i g n e d ,   s e a l e d ,   d e l i v e ...
4807    w h e n   a m b i t i o u s   n e w   y o r k ...
4808    e v e r   s i n c e   t h e   s e c o n d   g ...
Name: tags, Length: 4779, dtype: str

In [ ]:
movies['tags'].apply(type).value_counts()

tags
<class 'str'>    4779
Name: count, dtype: int64

In [ ]:
movies['tags'].iloc[0]

'i n   t h e   2 2 n d   c e n t u r y ,   a   p a r a p l e g i c   m a r i n e   i s   d i s p a t c h e d   t o   t h e   m o o n   p a n d o r a   o n   a   u n i q u e   m i s s i o n ,   b u t   b e c o m e s   t o r n   b e t w e e n   f o l l o w i n g   o r d e r s   a n d   p r o t e c t i n g   a n   a l i e n   c i v i l i z a t i o n .   a c t i o n   a d v e n t u r e   f a n t a s y   s c i e n c e f i c t i o n   c u l t u r e c l a s h   f u t u r e   s p a c e w a r   s p a c e c o l o n y   s o c i e t y   s p a c e t r a v e l   f u t u r i s t i c   r o m a n c e   s p a c e   a l i e n   t r i b e   a l i e n p l a n e t   c g i   m a r i n e   s o l d i e r   b a t t l e   l o v e a f f a i r   a n t i w a r   p o w e r r e l a t i o n s   m i n d a n d s o u l   3 d   s a m w o r t h i n g t o n   z o e s a l d a n a   s i g o u r n e y w e a v e r   j a m e s c a m e r o n   e n t e r   t h e   w o r l d   o f   p a n d o r a .'

In [29]:
movies.head(60)

,genres,id,keywords,overview,title,tagline,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"Lost in our world, found in another.","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]
5,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",559,"[dual identity, amnesia, sandstorm, love of on...",The seemingly invincible Spider-Man goes up ag...,Spider-Man 3,The battle within.,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...",[Sam Raimi]
6,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",38757,"[hostage, magic, horse, fairy tale, musical, p...",When the kingdom's most wanted-and most charmi...,Tangled,They're taking adventure to new lengths.,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...",[Byron Howard]
7,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",99861,"[marvel comic, sequel, superhero, based on com...",When Tony Stark tries to jumpstart a dormant p...,Avengers: Age of Ultron,A New Age Has Come.,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...",[Joss Whedon]
8,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",767,"[witch, magic, broom, school of witchcraft, wi...","As Harry begins his sixth year at Hogwarts, he...",Harry Potter and the Half-Blood Prince,Dark Secrets Revealed,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...",[David Yates]
9,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",209112,"[dc comics, vigilante, superhero, based on com...",Fearing the actions of a god-like Super Hero l...,Batman v Superman: Dawn of Justice,Justice or revenge,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...",[Zack Snyder]
10,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",1452,"[saving the world, dc comics, invulnerability,...",Superman returns to discover his 5-year absenc...,Superman Returns,NaN,"[{""cast_id"": 3, ""character"": ""Superman / Clark...",[Bryan Singer]
11,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",10764,"[killing, undercover, secret agent, british se...",Quantum of Solace continues the adventures of ...,Quantum of Solace,"For love, for hate, for justice, for revenge.","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Marc Forster]
12,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",58,"[witch, fortune teller, bondage, exotic island...",Captain Jack Sparrow works his way out of a bl...,Pirates of the Caribbean: Dead Man's Chest,Jack is back!,"[{""cast_id"": 37, ""character"": ""Captain Jack Sp...",[Gore Verbinski]
13,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",57201,"[texas, horse, survivor, texas ranger, partner...",The Texas Rangers chase down a gang of outlaws...,The Lone Ranger,Never Take Off the Mask,"[{""cast_id"": 4, ""character"": ""Tonto"", ""credit_...",[Gore Verbinski]
14,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49521,"[saving the world, dc comics, superhero, based...",A young boy learns that he has extraordinary p...,Man of Steel,You will believe that a man can fly.,"[{""cast_id"": 2, ""character"": ""Clark Kent / Kal...",[Zack Snyder]
15,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",2454,"[based on novel, fictional place, brother sist...",One year after their incredible adventures in ...,The Chronicles of Narnia: Prince Caspian,Hope has a new face.,"[{""cast_id"": 1, ""character"": ""Prince Caspian"",...",[Andrew Adamson]
16,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",24428,"[new york, shield, marvel comic, superhero, ba...",When an unexpected enemy emerges and threatens...,The Avengers,Some assembly required.,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...",[Joss Whedon]
17,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",1865,"[sea, captain, mutiny, sword, prime minister, ...",Captain Jack Sparrow crosses paths with a woma...,Pirates of the Caribbean: On Stranger Tides,Live Forever Or Die Trying.,"[{""cast_id"": 15, ""character"": ""Captain Jack Sp...",[Rob Marshall]
18,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",41154,"[time travel, time machine, alien, fictional g...",Agents J (Will Smith) and K (Tommy Lee Jones) ...,Men in Black 3,They are back... in time.,"[{""cast_id"": 4, ""character"": ""Agent J"", ""credi...",[Barry Sonnenfeld]
19,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",122917,"[corruption, elves, dwarves, orcs, middle-eart...",Immediately after the events of The Desolation...,The Hobbit: The Battle of the Five Armies,Witness the defining chapter of the Middle-Ear...,"[{""cast_id"": 10, ""character"": ""Bilbo Baggins"",...",[Peter Jackson]
20,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",1930,"[loss of father, vigilante, serum, marvel comi...",Peter Parker is an outcast high schooler aband...,The Amazing Spider-Man,The untold story begins.,"[{""cast_id"": 56, ""character"": ""Peter Parker / ...",[Marc Webb]
21,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",20662,"[robin hood, archer, knight, sherwood forest, ...",When soldier Robin happens upon the dying Robe...,Robin Hood,"Rise and rise again, until lambs become lions.","[{""cast_id"": 1, ""character"": ""Robin Longstride...",[Ridley Scott]
22,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",57158,"[elves, dwarves, orcs, hobbit, dragon, wizard,...","The Dwarves, Bilbo and Gandalf have successful...",The Hobbit: The Desolation of Smaug,Beyond darkness... beyond desolation... lies t...,"[{""cast_id"": 3, ""character"": ""Bilbo Baggins"", ...",[Peter Jackson]
23,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",2268,"[england, compass, experiment, lordship, uncle...","After overhearing a shocking secret, precociou...",The Golden Compass,There are worlds beyond our own - the compass ...,"[{""cast_id"": 43, ""character"": ""Lyra Belacqua"",...",[Chris Weitz]
24,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",254,"[film business, screenplay, show business, fil...","In 1933 New York, an overly ambitious movie pr...",King Kong,The eighth wonder of the world.,"[{""cast_id"": 5, ""character"": ""Ann Darrow"", ""cr...",[Peter Jackson]
25,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",597,"[shipwreck, iceberg, ship, panic, titanic, oce...","84 years later, a 101-year-old woman named Ros...",Titanic,Nothing on Earth could come between them.,"[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...",[James Cameron]
26,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",271110,"[civil war, war, marvel comic, sequel, superhe...","Following the events of Age of Ultron, the col...",Captain America: Civil War,Divided We Fall,"[{""cast_id"": 9, ""character"": ""Steve Rogers / C...",[Anthony Russo]
27,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...",44833,"[fight, u.s. navy, mind reading, hong kong, so...","When mankind beams a radio signal into space, ...",Battleship,The Battle for Earth Begins at Sea,"[{""cast_id"": 3, ""character"": ""Lieutenant Alex ...",[Peter Berg]
28,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",135397,"[monster, dna, tyrannosaurus rex, velociraptor...",Twenty-two years after the events of Jurassic ...,Jurassic World,The park is open.,"[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...",[Colin Trevorrow]
29,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",37724,"[spy, secret agent, sociopath, killer, art gal...",When Bond's latest assignment goes gravely wro...,Skyfall,Think on your sins.,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
30,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",558,"[dual identity, love of one's life, pizza boy,...",Peter Parker is going through a major identity...,Spider-Man 2,There's a hero in all of us.,"[{""cast_id"": 33, ""character"": ""Peter Parker / ...",[Sam Raimi]
31,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",68721,"[terrorist, war on terror, tennessee, malibu, ...",When Tony Stark's world is torn apart by a for...,Iron Man 3,Unleash the power behind the armor.,"[{""cast_id"": 40, ""character"": ""Tony Stark / Ir...",[Shane Black]
32,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 14, ""...",12155,"[based on novel, fictional place, queen, fanta...","Alice, an unpretentious and individual 19-year...",Alice in Wonderland,You're invited to a very important date.,"[{""cast_id"": 7, ""character"": ""Alice Kingsleigh...",[Tim Burton]
33,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",36668,"[mutant, marvel comic, based on comic book, su...","When a cure is found to treat mutations, lines...",X-Men: The Last Stand,Take a Stand,"[{""cast_id"": 4, ""character"": ""Logan / Wolverin...",[Brett Ratner]
34,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",62211,"[monster, dormitory, games, animation, best fr...",A look at the relationship between Mike and Su...,Monsters University,School never looked this scary.,"[{""cast_id"": 6, ""character"": ""Michael \""Mike\""...",[Dan Scanlon]
35,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",8373,"[egypt, sun, chaos, symbol, artifact, transfor...",Sam Witwicky leaves the Autobots behind for a ...,Transformers: Revenge of the Fallen,Revenge is coming.,"[{""cast_id"": 5, ""character"": ""Sam Witwicky"", ""...",[Michael Bay]
36,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",91314,"[sequel, alien, transformers, giant robot, rob...","As humanity picks up the pieces, following the...",Transformers: Age of Extinction,This is not war. It's extinction.,"[{""cast_id"": 6, ""character"": ""Cade Yeager"", ""c...",[Michael Bay]
37,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",68728,"[circus, witch, magic, hope, illusion, lost, m...","Oscar Diggs, a small-time circus illusionist a...",Oz: The Great and Powerful,"In Oz, nothing is what it seems","[{""cast_id"": 6, ""character"": ""Oz"", ""credit_id""...",[Sam Raimi]
38,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",102382,"[obsession, marvel comic, sequel, based on com...","For Peter Parker, life is busy. Between taking...",The Amazing Spider-Man 2,No more secrets.,"[{""cast_id"": 3, ""character"": ""Peter Parker / S...",[Marc Webb]
39,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",20526,"[artificial intelligence, secret identity, com...","Sam Flynn, the tech-savvy and daring son of Ke...",TRON: Legacy,The Game Has Changed.,"[{""cast_id"": 44, ""character"": ""Sam Flynn"", ""cr...",[Joseph Kosinski]
40,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",49013,"[car race, sequel, comedy, anthropomorphism, b...",Star race car Lightning McQueen and his pal Ma...,Cars 2,Ka-ciao!,"[{""cast_id"": 4, ""character"": ""Lightning McQuee...",[John Lasseter]
41,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",44912,"[dc comics, transformation, superhero, alien, ...","For centuries, a small but powerful force of w...",Green Lantern,"In our darkest hour, there will be light.","[{""cast_id"": 6, ""character"": ""Hal Jordan / Gre...",[Martin Campbell]
42,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",10193,"[hostage, college, toy, barbie, animation, esc...","Woody, Buzz, and the rest of Andy's toys haven...",Toy Story 3,No toy gets left behind.,"[{""cast_id"": 6, ""character"": ""Woody (voice)"", ...",[Lee Unkrich]
43,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",534,"[saving the world, artificial intelligence, pr...","All grown up in post-apocalyptic 2018, John Co...",Terminator Salvation,The End Begins.,"[{""cast_id"": 18, ""character"": ""John Connor"", ""...",[McG]
44,"[{""id"": 28, ""name"": ""Action""}]",168259,"[car race, speed, revenge, suspense, car, race...",Deckard Shaw seeks revenge against Dominic Tor...,Furious 7,Vengeance Hits Home,"[{""cast_id"": 17, ""character"": ""Dominic Toretto...",[James Wan]
45,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",72190,"[dystopia, apocalypse, zombie, nuclear weapons...",Life for former United Nations investigator Ge...,World War Z,Remember Philly!,"[{""cast_id"": 4, ""character"": ""Gerry Lane"", ""cr...",[Marc Forster]
46,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",127585,"[1970s, mutant, time travel, marvel comic, bas...",The ultimate X-Men ensemble fights a war for t...,X-Men: Days of Future Past,"To save the future, they must alter the past","[{""cast_id"": 9, ""character"": ""Logan / Wolverin...",[Bryan Singer]
47,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",54138,"[spacecraft, friendship, sequel, futuristic, s...",When the crew of the Enterprise is called back...,Star Trek Into Darkness,Earth Will Fall,"[{""cast_id"": 2, ""character"": ""James T. Kirk"", ...",[J.J. Abrams]
48,"[{""id"": 28, ""name"": ""Action""}, {""id"": 10751, ""...",81005,"[based on fairy tale, giant]",The story of an ancient war that is reignited ...,Jack the Giant Slayer,Prepare for a giant adventure,"[{""cast_id"": 7, ""character"": ""Jack"", ""credit_i...",[Bryan Singer]
49,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",64682,"[based on novel, infidelity, obsession, hope, 3d]",An adaptation of F. Scott Fitzgerald's Long Is...,The Great Gatsby,Reserving judgments is a matter of infinite ho...,"[{""cast_id"": 2, ""character"": ""Jay Gatsby"", ""cr...",[Baz Luhrmann]
50,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",9543,"[persia, sandstorm, brother against brother, a...",A rogue prince reluctantly joins forces with a...,Prince of Persia: The Sands of Time,Defy the Future,"[{""cast_id"": 5, ""character"": ""Prince Dastan"", ...",[Mike Newell]
51,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",68726,"[dystopia, giant robot, giant monster, apocaly...","When legions of monstrous creatures, known as ...",Pacific Rim,"To Fight Monsters, We Created Monsters","[{""cast_id"": 2, ""character"": ""Stacker Pentecos...",[Guillermo del Toro]
52,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""na...",38356,"[moon, spacecraft, traitor, bodyguard, alien p...",Sam Witwicky takes his first tenuous steps int...,Transformers: Dark of the Moon,The invasion we always feared. An enemy we nev...,"[{""cast_id"": 3, ""character"": ""Sam Witwicky"", ""...",[Michael Bay]
53,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",217,"[saving the world, riddle, whip, treasure, mex...","Set during the Cold War, the Soviets – led by ...",Indiana Jones and the Kingdom of the Crystal S...,The adventure continues . . .,"[{""cast_id"": 4, ""character"": ""Indiana Jones"", ...",[Steven Spielberg]
54,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 16, ""...",105864,"[tyrannosaurus rex, friends, alternate history...",An epic journey into the world of dinosaurs wh...,The Good Dinosaur,Little Arms With Big Attitude,"[{""cast_id"": 20, ""character"": ""Arlo (voice)"", ...",[Peter Sohn]
55,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 12, ""...",62177,"[scotland, rebel, bravery, kingdom, archer, wi...",Brave is set in the mystical Scottish Highland...,Brave,Change your fate.,"[{""cast_id"": 1, ""character"": ""M\u00e9rida (voi...",[Brenda Chapman]
56,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",188927,"[sequel, stranded, hatred, space opera]",The USS Enterprise crew explores the furthest ...,Star Trek Beyond,NaN,"[{""cast_id"": 9, ""character"": ""James T. Kirk"", ...",[Justin Lin]
57,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",10681,[romantic comedy],WALL·E is the last robot left on an Earth that...,WALL·E,An adventure beyond the ordinar-E.,"[{""cast_id"": 12, ""character"": ""WALL\u00b7E / M...",[Andrew Stanton]
58,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",5174,[ambassador],After an attempted assassination on Ambassador...,Rush Hour 3,The Rush Is On!,"[{""cast_id"": 2, ""character"": ""Det. James Carte...",[Brett Ratner]
59,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",14161,"[civilization, natural disaster, end of the wo...","Dr. Adrian Helmsley, part of a worldwide geoph...",2012,We Were Warned.,"[{""cast_id"": 1, ""character"": ""Jackson Curtis"",...",[Roland Emmerich]